name: coil_counter
description: Coil winding counter using phone sensors
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^5.0.0
  provider: ^6.0.5
  fl_chart: ^0.68.0
  audioplayers: ^6.0.0

flutter:
  uses-material-design: true
