name: coil_counter
description: Professional Coil Winding Counter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.1
  provider: ^6.1.2
  fl_chart: ^0.69.0
  audioplayers: ^6.1.0
  vibration: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/beep.mp3
